services:
  backend:
    build: ./backend
    ports:
      - "8089:8000"
    environment:
      MONGODB_URL: ${MONGODB_URL}
      MONGODB_DB: ${MONGODB_DB:-lifemaxxing-prod}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM:-HS256}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-10080}
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
